### ISSUE TITLE
Failed at the apiai-webhook-template-nodejs@0.0.1 start script 'functions deploy yourAction --trigger-http'.

### ISSUE THREAD

**Issue by yingchun1** [actions-on-google/dialogflow-webhook-boilerplate-nodejs#1]
i followed the step that in detail page, but when run gcloud app deploy, it throw below error trace:
Updating service [default]...failed.                                                                                           
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:

> apiai-webhook-template-nodejs@0.0.1 start /app
> functions deploy yourAction --trigger-http

sh: 1: functions: not found

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! apiai-webhook-template-nodejs@0.0.1 start: `functions deploy yourAction --trigger-http`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the apiai-webhook-template-nodejs@0.0.1 start script 'functions deploy yourAction --trigger-http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apiai-webhook-template-nodejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     functions deploy yourAction --trigger-http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apiai-webhook-template-nodejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apiai-webhook-template-nodejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by sandyjoshi** [comment]
do you have https://www.npmjs.com/package/@google-cloud/functions-emulator installed ? if not try `npm install -g @google-cloud/functions-emulator`

**Comment by sg-shashank** [comment]
Even after installing google-cloud/functions-emulator am still getting the same error: ERROR: (gcloud.app.deploy) Error Response: [9]

**Comment by peternann** [comment]
I'm having the same problem. npm install as recommended by @sandyjoshi doesn't help.

I don't see why I should install "functions-emulator" - I don't want to emulate GCP, I want to actually run in GCP.

I believe 'functions' is supposed to be an executable in the GCP server/docker environment, right? How is this going wrong... Weird...

**Comment by peternann** [comment]
I've figured out what is going on here. The instructions at the following link are out of date (at the time of writing): https://developers.google.com/actions/samples/
The instructions say to use "gcloud app deploy", but the sample have all been moved to a different GCP service - Basically "gcloud beta functions" is the key - as you will see in the package.json files.

Confusing and annoying - Yes!

Also, I hear that Google are moving all the samples (again) to Firebase, as currently outlined in the 'Getting Started' page here: https://developers.google.com/actions/get-started/deploy-fulfillment

So there is that 3rd option, and where we should all be aiming going forward it seems...

I hope this helps someone.

**Comment by Canain** [comment]
We have recently updated almost all the samples to use Firebase Functions since we determined that it is the easiest and free webhook deployment service to use currently.

Try deploying the updated sample code using the updated readme.

Feel free to open another issue if you encounter any difficulties.
