### ISSUE TITLE
Not getting "Hello, World!" message

### ISSUE THREAD

**Issue by hchiam** [actions-on-google/dialogflow-webhook-boilerplate-nodejs#13]
Instead of the ['Hello, World!'](https://github.com/actions-on-google/dialogflow-webhook-boilerplate-nodejs/blob/master/functions/index.js#L22) message, I get a response found listed for the Default Welcome Intent in Dialogflow. I then tried deleting the test responses in Dialogflow, but that causes another error. Any help would be appreciated. Catching up on the V2 API, specifically for webhooks.

**Comment by Fleker** [comment]
Did you enable Fulfillment for that intent? What error do you get?

**Comment by hchiam** [comment]
Yes, in Dialogflow, I have Webhook enabled under Fulfillment, and I entered the URL that I got from the `firebase deploy` command. 

**With it as-is:** no error. _But_ it shows a text response instead of the desired webhook response.

**If I delete text responses in Dialogflow:** The Actions on Google simulator says `My test app isn't responding right now. Try again soon.` and the error log says: 
```
MalformedResponse Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: ... and intentId: ... 
```

**Comment by Fleker** [comment]
Is your fulfillment URL in the pattern `https://<project-id>.us-central1.cloudfunctions.net`?

**Comment by hchiam** [comment]
The URL generated by the CLI command looks like this: `https://console.firebase.google.com/project/dialogflow-webhook-boile-.../overview`

**Comment by Fleker** [comment]
Okay, that's not the right link. You can visit the link, but you'll only see the Firebase console.

You can either use the pattern `https://us-central1-<project-id>.cloudfunctions.net/<function-name>`
or in the console you can see the full URL:

![image](https://user-images.githubusercontent.com/3291635/65888310-49c37f00-e36d-11e9-8a95-63f9a788b10d.png)

**Comment by hchiam** [comment]
That fixed it. Thanks @Fleker!
