### ISSUE TITLE
Queries selected from lists not recognized by assistant to trigger intents

### ISSUE THREAD

**Issue by ghost** [actions-on-google/dialogflow-webhook-boilerplate-nodejs#4]
I ran into an issue using a list item in the simulator and iOS assistant app.
When selecting a response from a list, after the title of the list item is sent as a query, the default fallback intent is given rather than the intended intent.
Worth noting is that if I include a suggestion chip set to send the same query and select it from the same conversation state, it will trigger the desired intent.
Also, if the conversation state changes so that the list is not the latest item in the conversation, then selecting the list item will trigger the desired intent.

**Comment by LeonNicholls** [comment]
You need to use the "actions_intent_OPTION" event for the item selection intent in the API.AI agent. Take a look at the sample app: https://github.com/actions-on-google/conversation-components-nodejs
